name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup ElasticSearch
      uses: getong/elasticsearch-action@v1
      with:
        # Version of elasticsearch to use
        elasticsearch version: 7.4.1
        # The port of host
        host port: 9200
        # The port of container
        container port: 9200
        # the discovery.type envionment
        discovery type: single-node
    - name: Cache node modules
      uses: actions/cache@v1.1.2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Cache mongo in memory
      uses: actions/cache@v1.1.2
      with:
        path: ~/.mongodb-binaries
        key: '6.2.4' #mongo in memory version  
    - run: yarn install
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:9200/ #check if elastic is up
    - run: ./cc-test-reporter before-build #prepare codeclimate code coverage reporter
    - run: ./node_modules/.bin/jest --coverage --maxWorkers=2 #run tests
    - run: ./cc-test-reporter after-build --exit-code $? #send codecoverage
    env:
      CC_TEST_REPORTER_ID: 61434ccfc3eeb2ed7b9cfec1d61c4e0ca115a32c1eebfefe404d1ecb77d73358 #codelimate api key  
