name: Uwazi CI

on: [push]

jobs:
  uinit_test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.4.1
        ports:
        - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    strategy:
      matrix:
        node-version: [10.17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1.1.2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Cache mongo in memory
      uses: actions/cache@v1.1.2
      with:
        path: ~/.mongodb-binaries
        key: '6.2.4' #mongo in memory version
    - name: Verify Elasticsearch connection from host
      run: |
        echo $ELASTICSEARCH_URL
        curl -fsSL "$ELASTICSEARCH_URL/_cat/health?h=status"
    - name: install dependencies  
      run: yarn install
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build #prepare codeclimate code coverage reporter
    - run: ./node_modules/.bin/jest --coverage --maxWorkers=2 #run tests
    - run: ./cc-test-reporter after-build --exit-code $? #send codecoverage
    env:
      CC_TEST_REPORTER_ID: 61434ccfc3eeb2ed7b9cfec1d61c4e0ca115a32c1eebfefe404d1ecb77d73358 #codelimate api key 
      ELASTICSEARCH_URL: http://localhost:${{ jobs.unit_test.services.elasticsearch.ports[9200] }}
